# Alternative YAML without top-level outputs

$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
display_name: Spam-Classifier-Pipeline

settings:
  default_compute: azureml:spam-cluster

inputs:
  raw_data_input:
    type: uri_file
    path: azureml:Spam_HAM:1

jobs:

  preprocess_step:
    type: command
    component: ./components/preprocess/preprocess.yaml
    inputs:
      raw_data: ${{parent.inputs.raw_data_input}}

  train_step:
    type: command
    component: ./components/train/train.yaml
    inputs:
      clean_data_input: ${{parent.jobs.preprocess_step.outputs.cleaned}}
    outputs:
      # Define the output directly on the step (not mapped to parent.outputs)
      model_output:
        type: uri_folder

  register_step:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.21
    inputs:
      model_name: spam-classifier
      model_type: custom_model
      model_path: ${{parent.jobs.train_step.outputs.model_output}} # Reference remains the same
    outputs:
      # Define the output directly on the step (not mapped to parent.outputs)
      registration_details_folder:
        type: uri_folder