$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
display_name: Spam-Classifier-Pipeline

settings:
  default_compute: azureml:spam-cluster

inputs:
  raw_data_input:
    type: uri_file
    path: azureml:Spam_HAM:1

# No top-level outputs needed for your goal
# outputs: 

jobs:

  preprocess_step:
    type: command
    component: ./components/preprocess/preprocess.yaml
    inputs:
      raw_data: ${{parent.inputs.raw_data_input}}

  train_step:
    type: command
    component: ./components/train/train.yaml
    inputs:
      clean_data_input: ${{parent.jobs.preprocess_step.outputs.cleaned}}
    # WE REMOVED THE OUTPUTS SECTION HERE
    # We don't need to explicitly list 'outputs' unless mapping to parent.
    # The component 'output_folder' is automatically available to the next step.

  register_step:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.21
    identity:
      type: user_identity
    # 👆 END ADDITION
    inputs:
      # 1. Matches the name in your GitHub Action download script
      model_name: spam-classifier 
      model_type: custom_model
      # 2. FIX: Reference the Component Output Name 'output_folder'
      model_path: ${{parent.jobs.train_step.outputs.output_folder}}