$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
display_name: Spam-Classifier-Pipeline

settings:
  default_compute: azureml:spam-cluster

inputs:
  raw_data_input:
    type: uri_file
    path: azureml:Spam_HAM:1

jobs:
  preprocess_step:
    type: command
    code: ./src
    environment:
      conda_file: ./src/conda.yaml
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

    command: >-
      python preprocess.py
      --raw_data ${{inputs.raw_data}}
      --output_data ${{outputs.cleaned}}

    inputs:
      raw_data: ${{parent.inputs.raw_data_input}}

    outputs:
      cleaned:
        type: uri_folder

  train_step:
    type: command
    code: ./src
    environment:
      conda_file: ./src/conda.yaml
      image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:latest

    command: >-
      python train_pipeline.py
      --clean_data ${{inputs.clean_data}}
      --model_output ${{outputs.model_output}}

    inputs:
      clean_data_input: ${{parent.jobs.preprocess_step.outputs.cleaned}}

    outputs:
      model_output:
        type: mlflow_model         # <---- REGISTER MODEL AUTOMATICALLY
        mode: upload               # <---- REQUIRED
        name: spam-classifier      # <---- REGISTERED MODEL NAME
